### PR TITLE
Multi deck support

### LINKED ISSUE #18: All cards added to the first deck name when multiple decks are added to a package.
Dear KerrickStaley,

Thank you for sharing your library.
I think I might have found an issue.

Example code:
```
data = {
    'deck1':
    [{
    'a': 'content deck 1 a1',
    'b': 'content deck 1 b1'
    },
    {
    'a': 'content deck 1 a2',
    'b': 'content deck 1 b2'
    }],
    'deck2':
     [{
    'a': 'content deck 2 a1',
    'b': 'content deck 2 b1'
    },
    {
    'a': 'content deck 2 a2',
    'b': 'content deck 2 b2'
    }],
    'deck3':
     [{
    'a': 'content deck 3 a1',
    'b': 'content deck 3 b1'
    },
    {
    'a': 'content deck 3 a2',
    'b': 'content deck 3 b2'
    }]  
}

# Create the model
a_to_b = genanki.Model(
    2043134337, # unique identifier
    'a-to-b', # human readable name
    fields = [ 
    {'name': 'a'},
    {'name': 'b'},
    ],
    templates=[
    {
      'name': 'Card 1',
      'qfmt': '{{a}}',
      'afmt': '{{FrontSide}}<hr id="answer">{{b}}',
    },
    ]
)

decks = []
for deck_name in data:
    deck = genanki.Deck(
      2043134340,
      deck_name
    )

    # Add the notes
    for note in data[deck_name]:
      note = genanki.Note(
        model=a_to_b,
        fields=[note.get('a',''),
                note.get('b',''),
               ])
      deck.add_note(note)
    decks.append(deck)

# Create the file
genanki.Package(decks).write_to_file('output.apkg')
```
When I then load this apkg file into Anki, Anki adds all 6 cards that should be in deck1, deck2 and deck3 into only deck1.

### PR DESCRIPTION
**Pull request by marccarre**
This PR adds multideck support with the proposed solution from issue https://github.com/kerrickstaley/genanki/issues/18#issuecomment-443016527.

It follows-up on and supersedes #25,
- initially opened by @sciencemanx (thank you very much! ✨), 
- reviewed by @kerrickstaley (thank you very much too! ✨), and
- improves #25 based on the feedback made, which I'm guessing @sciencemanx didn't have time to address, given no reply to https://github.com/kerrickstaley/genanki/pull/25#issuecomment-471979254 after ~1 week, and given feedback was made almost two months ago.

**Disclaimer**: apologies in advance to you @sciencemanx if you had plans to reply on/keep working on #25! 🙂I just need to create new Anki decks programmatically very soon, and issue #18 is currently a blocker.

Fixes #18. Closes #25.

### CODE REVIEW

**Comment by marccarre** [comment]
@kerrickstaley, if you're happy with this PR, would it be possible to create a new release of `genanki` once it is merged? 😊

**Comment by marccarre** [comment]
Anyone alive? 👋🙂

**Comment by marccarre** [comment]
In case anyone out there is interested in using this patch, I've just made it available via PyPi:
```console
pip install genanki-marccarre==0.6.4
```
This is essentially this repository's `master` 6d173fcd8a50b29164d733fce750276bc9a9f39d version, with this PR on top of it, and a few smaller changes to be able to test and push to PyPi under a different package name. See also: https://github.com/kerrickstaley/genanki/compare/6d173fcd8a50b29164d733fce750276bc9a9f39d...marccarre:0.6.4 and my fork's sources for [0.6.4](https://github.com/marccarre/genanki/tree/0.6.4).

**Comment by kerrickstaley** [comment]
I fixed this bug in https://github.com/kerrickstaley/genanki/commit/53bc7b4e1be3f19af022ef293faa0040bc5c35ee, and I've pushed the new version (0.6.4) to PyPI.

I ended up rewriting the patch because this PR refactors things in a way that doesn't match the existing code style, and which may make it harder to maintain the code long-term.

Sorry for the delay on fixing this, and thanks for your help!

**Pull request closed without merging**
