### PR TITLE
Fix Card Order and Date of Creation Bug With Indexes

### PR DESCRIPTION
**Pull request by georgjaehnig**
I've implemented the solution suggested here: https://github.com/kerrickstaley/genanki/pull/30#discussion_r293843839

### CODE REVIEW

**Comment by kerrickstaley** [comment]
Hi @georgjaehnig, can you figure out why the Travis CI tests are failing? I can't merge this PR until they pass. Let me know if you need help.

**Comment by kerrickstaley** [comment]
Also, you should add a test that exercises this functionality and confirms that the code behaves as expected. Let me know if you need help with that too.

**Comment by georgjaehnig** [comment]
Hi, thanks for your offer to help. I've found the problem. The error

    sqlite3.IntegrityError: UNIQUE constraint failed: notes.id

comes from 

    deck1.add_note(note)
    deck2.add_note(note)

in https://github.com/kerrickstaley/genanki/blob/master/tests/test_genanki.py#L147

The notes.id generated by the timestamp and the note index *within the deck*. Since there are two different decks here, one created right after the other the `notes.id` is the same.

I only thought about notes being generated at the same time that come from the same deck – I didn't think about different decks.

So we would in fact need to track all the notes created, beyond deck instances. I'm not sure how to do this best.

Ideas for a solution that came to my mind:

- Have an instance-independent counter within `class Note` (guess that's not possible)
- Before every `cursor.execute('INSERT INTO`, retrieve the last `notes.id` and check if it would collide (maybe too time-consuming)?

It's all kind of messy because Anki puts ID and creation date into the same field. :(

**Comment by georgjaehnig** [comment]
> So we would in fact need to track all the notes created, beyond deck instances. I'm not sure how to do this best.

Another idea: Before generating any *sequence* of notes (or cards):

- retrieve last note/card id from database
- set new id to max(last_id, timestamp)
- generate sequence of notes/cards starting from new id and then incrementing by 1 (simply by sql auto-increment).

This way, only at the beginning of the sequence we would read the db, the rest would run quickly.

Let me know what you think.

**Comment by aalemayhu** [comment]
@georgjaehnig Courtesy, ping. Is there any progress on this? 

Thanks!

**Comment by georgjaehnig** [comment]
Nope, I didn't work on it after the last comment. From what I roughly remember it was rather an issue with the test than with the actual code having errors.

**Comment by aalemayhu** [comment]
I see, I tried running the tests locally and they failed with the below summary. So you are probably right, they need to be updated. 

I also went ahead and tried to rebase against master from your branch. There were several merge conflicts, I am not familiar with the genanki code and ended up giving up 🙂 Is there any chance you could resolve the conflicts? I can then look into the tests, thank you 🙏🏾 

```
================================================================ short test summary info ================================================================
FAILED tests/test_genanki.py::TestWithCollection::test_multi_deck_package - sqlite3.IntegrityError: UNIQUE constraint failed: notes.id
FAILED tests/test_genanki.py::TestWithCollection::test_card_suspend - assert [1606578548000, 1606578548001] == [1, 2]
======================================================= 2 failed, 14 passed, 20 warnings in 1.34s =======================================================

```

**Comment by georgjaehnig** [comment]
OK, I have resolved the merge conflict. And generation also worked on one of my projects. Let's see if the checks will pass.

**Comment by aalemayhu** [comment]
@georgjaehnig I appreciate you following up 👍🏾 I have created a pull request with some fixes, targeting your master branch. Hopefully we can get the outstanding failures resolved 🙂

**Comment by georgjaehnig** [comment]
Thanks! I have just scrolled up and noticed [this comment of mine](https://github.com/kerrickstaley/genanki/pull/35#issuecomment-514550112):

> The notes.id is generated by the timestamp and the note index note_idx within the deck. Since there are two different decks here, one created right after the other the notes.id is the same.

This means that we'd need a completely different approach, as is written in the comments below. [One idea was this](https://github.com/kerrickstaley/genanki/pull/35#issuecomment-514666021).

In the meantime, I also thought to maybe do it the hacky way with `sleep()`? Apparently, you can sleep also only milliseconds.  I've added a line for testing but the tests still fail. :(

**Comment by kerrickstaley** [comment]
I fixed the note/card "Added" date issue (https://github.com/kerrickstaley/genanki/issues/29) in https://github.com/kerrickstaley/genanki/commit/f1c738ab59b216d304d753a4c86fb09bcbbbf37b, and that fix has been released in genanki 0.10.0 which is now on PyPI (https://pypi.org/project/genanki/0.10.0/). I think this PR is now obsolete, so I'm going to close it (but let me know if this is a mistake).

**Pull request closed without merging**
