### PR TITLE
Add multideck support and reorganize classes into files

### PR DESCRIPTION
**Pull request by sciencemanx**
This makes the code easier to read and navigate through! Thanks.

### CODE REVIEW

**Comment by sciencemanx** [comment]
I'll fix these errors -- whats the best way to run the test locally tho?

**Comment by sciencemanx** [comment]
Apparently you can't stack PR's in Github so I'm lumping this all into one.

**Comment by sciencemanx** [comment]
@kerrickstaley Bump

**Comment by kerrickstaley** [comment]
@sciencemanx please split this into multiple PRs. I think there should be at least 3, one to fix the multideck issue, one to add the gitignore, and one to do the refactor.

If you want to get them reviewed in parallel, you can do this:
1. Create a PR for the multideck issue.
2. Create a new branch for the refactor, based off the multideck PR branch.
3. When opening the PR for the refactor branch, choose the base branch to be your multideck PR branch, instead of kerrickstaley:master.
4. Tag me in the refactor PR, because I think it will appear in your repo on GitHub and not in mine.
5. Once I've reviewed both the multideck PR and the refactor PR, I'll commit them as two separate commits.

If you don't want to do that, just open the multideck and gitignore PRs, I'll review and commit them, then you can open the refactor PR.

**Comment by sciencemanx** [comment]
Sure I can do that -- however I think it will be easiest if we put the refactor and gitignore first, followed by the multideck support.

**Comment by sciencemanx** [comment]
@kerrickstaley See #22 and #23

**Comment by waf** [comment]
@sciencemanx thanks for working on this. I was able to use your branch https://github.com/sciencemanx/genanki/tree/multi-deck-support to successfully generate a multi-deck collection. You saved me a lot of time, thank you!

**Pull request closed without merging**
